static int _glyph_20[] = {-1};
static int _glyph_21[] = {19, 8, 8, 8, 8, 8, 8, 16, -1};
static int _glyph_22[] = {18, 3, 5, 3, 5, 3, -1};
static int _glyph_23[] = {26, 3, 5, 3, 4, 1, 1, 1, 1, 1, 4, 3, 4, 1, 1, 1, 1, 1, 4, 3, 5, 3, -1};
static int _glyph_24[] = {27, 7, 1, 1, 1, 4, 2, 7, 1, 1, 7, 2, 4, 1, 1, 1, 7, -1};
static int _glyph_25[] = {18, 4, 3, 2, 3, 4, 3, 7, 8, 7, 7, 3, 5, 2, 2, 3, 4, -1};
static int _glyph_26[] = {34, 1, 6, 3, 5, 3, 6, 1, 6, 3, 2, 3, 4, 5, 1, 1, 2, -1};
static int _glyph_27[] = {18, 1, 1, 6, 1, 6, -1};
static int _glyph_28[] = {21, 7, 8, 7, 8, 8, 9, 8, 9, -1};
static int _glyph_29[] = {18, 9, 8, 9, 8, 8, 7, 8, 7, -1};
static int _glyph_2A[] = {34, 3, 6, 1, 5, 1, 1, 1, 1, 1, 5, 1, 6, 3, -1};
static int _glyph_2B[] = {35, 8, 6, 1, 1, 1, 1, 6, 8, -1};
static int _glyph_2C[] = {74, 1, 1, 6, 1, 6, -1};
static int _glyph_2D[] = {49, 1, 1, 1, 1, 1, -1};
static int _glyph_2E[] = {75, 7, 1, 1, 7, -1};
static int _glyph_2F[] = {22, 8, 7, 7, 7, 7, 7, 7, 8, -1};
static int _glyph_30[] = {19, 1, 6, 3, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 4, 3, 6, 1, -1};
static int _glyph_31[] = {19, 7, 1, 6, 2, 8, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
static int _glyph_32[] = {18, 1, 1, 1, 4, 5, 3, 5, 8, 7, 6, 1, 6, 7, 8, 1, 1, 1, 1, 1, -1};
static int _glyph_33[] = {17, 1, 1, 1, 1, 1, 8, 7, 7, 7, 1, 1, 9, 8, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_34[] = {21, 7, 1, 6, 2, 5, 3, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 7, 8, -1};
static int _glyph_35[] = {17, 1, 1, 1, 1, 1, 3, 8, 8, 2, 1, 1, 4, 1, 4, 8, 8, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_36[] = {19, 1, 1, 5, 7, 8, 8, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_37[] = {17, 1, 1, 1, 1, 1, 8, 7, 7, 8, 7, 8, 7, 8, -1};
static int _glyph_38[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 5, 4, 1, 1, 1, 4, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_39[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 4, 1, 4, 1, 1, 2, 8, 8, 7, 5, 1, 1, -1};
static int _glyph_3A[] = {35, 7, 1, 1, 7, 24, 7, 1, 1, 7, -1};
static int _glyph_3B[] = {35, 7, 1, 1, 7, 23, 1, 1, 6, 1, 6, -1};
static int _glyph_3C[] = {22, 7, 7, 7, 7, 9, 9, 9, 9, -1};
static int _glyph_3D[] = {41, 1, 1, 1, 1, 1, 19, 1, 1, 1, 1, 1, -1};
static int _glyph_3E[] = {17, 9, 9, 9, 9, 7, 7, 7, 7, -1};
static int _glyph_3F[] = {18, 1, 1, 1, 4, 5, 3, 5, 8, 7, 7, 8, 16, -1};
static int _glyph_40[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 3, 1, 1, 3, 2, 3, 3, 2, 2, 1, 3, 3, 2, 3, 9, 1, 1, 1, -1};
static int _glyph_41[] = {19, 1, 6, 3, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 1, 3, 5, 3, 5, 3, 5, -1};
static int _glyph_42[] = {16, 1, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 2, 1, 1, 1, 1, 1, -1};
static int _glyph_43[] = {18, 1, 1, 1, 4, 5, 3, 8, 8, 8, 8, 8, 5, 4, 1, 1, 1, -1};
static int _glyph_44[] = {16, 1, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 2, 1, 1, 1, 1, 1, -1};
static int _glyph_45[] = {17, 1, 1, 1, 1, 1, 3, 8, 8, 8, 1, 1, 1, 5, 8, 8, 8, 1, 1, 1, 1, 1, -1};
static int _glyph_46[] = {17, 1, 1, 1, 1, 1, 3, 8, 8, 8, 1, 1, 1, 5, 8, 8, 8, -1};
static int _glyph_47[] = {18, 1, 1, 1, 4, 5, 3, 8, 8, 8, 3, 1, 1, 3, 5, 3, 4, 1, 4, 1, 1, 2, -1};
static int _glyph_48[] = {17, 5, 3, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 1, 3, 5, 3, 5, 3, 5, 3, 5, -1};
static int _glyph_49[] = {17, 1, 1, 1, 1, 6, 8, 8, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
static int _glyph_4A[] = {19, 1, 1, 1, 7, 8, 8, 8, 8, 8, 4, 4, 5, 1, 1, -1};
static int _glyph_4B[] = {17, 5, 3, 4, 4, 3, 5, 2, 6, 1, 7, 2, 6, 3, 5, 4, 4, 5, -1};
static int _glyph_4C[] = {17, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, -1};
static int _glyph_4D[] = {16, 6, 2, 6, 2, 1, 4, 1, 2, 2, 2, 2, 2, 3, 3, 2, 3, 3, 2, 6, 2, 6, 2, 6, -1};
static int _glyph_4E[] = {17, 5, 3, 5, 3, 1, 4, 3, 2, 3, 3, 3, 2, 3, 4, 1, 3, 5, 3, 5, 3, 5, -1};
static int _glyph_4F[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_50[] = {17, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 4, 8, 8, 8, -1};
static int _glyph_51[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 2, 3, 3, 3, 2, 4, 1, 1, 1, 9, -1};
static int _glyph_52[] = {17, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 4, 2, 6, 3, 5, 4, 4, 5, -1};
static int _glyph_53[] = {18, 1, 1, 1, 4, 5, 3, 8, 9, 1, 1, 1, 9, 8, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_54[] = {16, 1, 1, 1, 1, 1, 1, 5, 8, 8, 8, 8, 8, 8, 8, -1};
static int _glyph_55[] = {17, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_56[] = {16, 6, 2, 6, 3, 4, 4, 4, 4, 4, 5, 2, 6, 2, 6, 2, 7, -1};
static int _glyph_57[] = {16, 6, 2, 6, 2, 6, 2, 6, 2, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 2, 3, 4, -1};
static int _glyph_58[] = {16, 6, 2, 6, 3, 4, 5, 2, 7, 7, 2, 5, 4, 3, 6, 2, 6, -1};
static int _glyph_59[] = {16, 6, 2, 6, 3, 4, 5, 2, 7, 8, 8, 8, 8, -1};
static int _glyph_5A[] = {17, 1, 1, 1, 1, 1, 8, 7, 7, 7, 7, 7, 8, 8, 1, 1, 1, 1, 1, -1};
static int _glyph_5B[] = {18, 1, 1, 1, 5, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, -1};
static int _glyph_5C[] = {16, 8, 9, 9, 9, 9, 9, 9, 8, -1};
static int _glyph_5D[] = {17, 1, 1, 1, 8, 8, 8, 8, 8, 8, 8, 5, 1, 1, 1, -1};
static int _glyph_5E[] = {19, 7, 2, 5, 4, -1};
static int _glyph_5F[] = {88, 1, 1, 1, 1, 1, 1, -1};
static int _glyph_60[] = {18, 1, 1, 7, 1, 9, -1};
static int _glyph_61[] = {42, 1, 1, 1, 9, 4, 1, 1, 1, 1, 3, 5, 3, 4, 1, 4, 1, 1, 2, -1};
static int _glyph_62[] = {17, 8, 8, 8, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 3, 1, 4, 3, 2, 1, 1, -1};
static int _glyph_63[] = {42, 1, 1, 1, 4, 5, 3, 8, 8, 5, 4, 1, 1, 1, -1};
static int _glyph_64[] = {22, 8, 8, 4, 1, 1, 2, 3, 4, 1, 3, 5, 3, 5, 3, 4, 1, 4, 1, 1, 2, -1};
static int _glyph_65[] = {42, 1, 1, 1, 4, 5, 3, 1, 1, 1, 1, 1, 3, 8, 5, 4, 1, 1, 1, -1};
static int _glyph_66[] = {19, 1, 1, 5, 4, 4, 8, 7, 1, 1, 1, 1, 5, 8, 8, 8, -1};
static int _glyph_67[] = {42, 1, 1, 2, 3, 4, 4, 4, 5, 1, 1, 5, 9, 1, 1, 1, 4, 5, 4, 1, 1, 1, -1};
static int _glyph_68[] = {17, 8, 8, 8, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 3, 5, 3, 5, -1};
static int _glyph_69[] = {27, 15, 1, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
static int _glyph_6A[] = {29, 15, 1, 8, 8, 8, 8, 4, 4, 4, 4, 5, 1, 1, -1};
static int _glyph_6B[] = {17, 8, 8, 8, 4, 4, 3, 5, 1, 1, 6, 3, 5, 4, 4, 5, -1};
static int _glyph_6C[] = {18, 1, 8, 8, 8, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
static int _glyph_6D[] = {40, 1, 1, 2, 1, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 3, 2, 6, -1};
static int _glyph_6E[] = {41, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 3, 5, 3, 5, -1};
static int _glyph_6F[] = {42, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_70[] = {41, 2, 1, 1, 4, 1, 4, 3, 5, 3, 1, 4, 3, 2, 1, 1, 4, 8, 8, -1};
static int _glyph_71[] = {42, 1, 1, 2, 3, 4, 1, 3, 5, 3, 4, 1, 4, 1, 1, 2, 8, 8, 8, -1};
static int _glyph_72[] = {41, 2, 1, 1, 5, 4, 4, 8, 8, 8, -1};
static int _glyph_73[] = {42, 1, 1, 1, 4, 5, 4, 1, 9, 1, 4, 5, 4, 1, 1, 1, -1};
static int _glyph_74[] = {26, 8, 7, 1, 1, 1, 1, 5, 8, 8, 8, 4, 5, 1, 1, -1};
static int _glyph_75[] = {41, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 1, 1, 2, -1};
static int _glyph_76[] = {41, 4, 4, 4, 4, 4, 5, 2, 6, 2, 7, -1};
static int _glyph_77[] = {40, 6, 2, 6, 2, 3, 3, 2, 3, 3, 2, 2, 2, 2, 3, 4, -1};
static int _glyph_78[] = {41, 5, 4, 3, 6, 1, 7, 1, 6, 3, 4, 5, -1};
static int _glyph_79[] = {41, 5, 3, 5, 3, 5, 3, 4, 1, 4, 1, 1, 2, 8, 3, 5, 4, 1, 1, 1, -1};
static int _glyph_7A[] = {41, 1, 1, 1, 1, 1, 7, 7, 7, 7, 7, 1, 1, 1, 1, 1, -1};
static int _glyph_7B[] = {20, 1, 1, 5, 8, 9, 6, 1, 9, 7, 8, 9, 1, 1, -1};
static int _glyph_7C[] = {19, 8, 8, 8, 8, 8, 8, 8, 8, -1};
static int _glyph_7D[] = {17, 1, 1, 9, 8, 7, 9, 1, 6, 9, 8, 5, 1, 1, -1};
static int _glyph_7E[] = {18, 3, 4, 2, 2, 4, 3, -1};
static int _glyph_7F[] = {-1};

int *system_font[] = 
{
  /* Fill in for the control characters */
  _glyph_20,	// 0
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,	// 8
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,	// 16
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,	// 24
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,
  _glyph_20,

  _glyph_20,	// 32
  _glyph_21,
  _glyph_22,
  _glyph_23,
  _glyph_24,
  _glyph_25,
  _glyph_26,
  _glyph_27,
  _glyph_28,
  _glyph_29,
  _glyph_2A,
  _glyph_2B,
  _glyph_2C,
  _glyph_2D,
  _glyph_2E,
  _glyph_2F,
  _glyph_30,
  _glyph_31,
  _glyph_32,
  _glyph_33,
  _glyph_34,
  _glyph_35,
  _glyph_36,
  _glyph_37,
  _glyph_38,
  _glyph_39,
  _glyph_3A,
  _glyph_3B,
  _glyph_3C,
  _glyph_3D,
  _glyph_3E,
  _glyph_3F,
  _glyph_40,
  _glyph_41,
  _glyph_42,
  _glyph_43,
  _glyph_44,
  _glyph_45,
  _glyph_46,
  _glyph_47,
  _glyph_48,
  _glyph_49,
  _glyph_4A,
  _glyph_4B,
  _glyph_4C,
  _glyph_4D,
  _glyph_4E,
  _glyph_4F,
  _glyph_50,
  _glyph_51,
  _glyph_52,
  _glyph_53,
  _glyph_54,
  _glyph_55,
  _glyph_56,
  _glyph_57,
  _glyph_58,
  _glyph_59,
  _glyph_5A,
  _glyph_5B,
  _glyph_5C,
  _glyph_5D,
  _glyph_5E,
  _glyph_5F,
  _glyph_60,
  _glyph_61,
  _glyph_62,
  _glyph_63,
  _glyph_64,
  _glyph_65,
  _glyph_66,
  _glyph_67,
  _glyph_68,
  _glyph_69,
  _glyph_6A,
  _glyph_6B,
  _glyph_6C,
  _glyph_6D,
  _glyph_6E,
  _glyph_6F,
  _glyph_70,
  _glyph_71,
  _glyph_72,
  _glyph_73,
  _glyph_74,
  _glyph_75,
  _glyph_76,
  _glyph_77,
  _glyph_78,
  _glyph_79,
  _glyph_7A,
  _glyph_7B,
  _glyph_7C,
  _glyph_7D,
  _glyph_7E,
  _glyph_7F
};

