//The New
void videoconfig_clicked();
void audioconfig_clicked();
void inputconfig_clicked();
void miscconfig_clicked();
void about_clicked();

GtkWidget* create_videoconfig();
GtkWidget* create_audioconfig();
GtkWidget* create_inputconfig();
GtkWidget* create_miscconfig();
GtkWidget* create_about();

//The Old
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_archselect (void);
GtkWidget* create_cheatwind (void);
//GtkWidget* create_about (void);
